# R package

## Introduction {-}

I created a R package to support my portfolio, following [The Whole Game demo](https://r-pkgs.org/whole-game.html) made by Hadley Wickham. The demo guided me through setting up my own package and helped me create something useful on my own after.

----

## Copopa {-}

To start a new package, a name is necessary. I combined my name, "portfolio" and "package" together into a fun word an checked availability with the {available} package. 

The name was available, so I set up the project and the github repository to get started.

A package to support my portfolio would reduce duplicated code. But scanning through my portfolio, I noticed that there wasn't a lot of code or duplicated code. Luckily, i found some that would work for this. The package that I made contains four functions:
<ul><li>multi_check() -> checks the data type of up to three datasets, or columns in it.</li>
<li>save_to_csv_rds() -> saves a data frame into CSV and RDS files.</li>
<li>mima() -> calculates the minimum and maximum of data.</li>
<li>mean_sd -> calculates the mean and standard deviation of data.</li></ul>
For the manual and contents of the package, please visit [the copopa github repository](https://github.com/coconiemel/copopa).

## Install and load {-}

```{r install and load package, eval = FALSE}

# Only if not obtained already
install.packages("devtools")
library(devtools)

# Installation
devtools::install_github("coconiemel/copopa")

# Load
library(copopa)

```



